apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-service
  template:
    metadata:
      labels:
        app: users-service
    spec:
      containers:
        - image: lorenzogl/users-service:GIT_SHA_SECRET
          imagePullPolicy: Always
          name: users-service
          readinessProbe:
            httpGet:
              path: /ping
              port: 7000
            initialDelaySeconds: 100
            failureThreshold: 5
            successThreshold: 1
            timeoutSeconds: 60
            periodSeconds: 60
          livenessProbe:
            httpGet:
              path: /ping
              port: 7000
            initialDelaySeconds: 300
            failureThreshold: 5
            successThreshold: 1
            timeoutSeconds: 60
            periodSeconds: 60
          env:
            - name: ENV_VAR_1
              value: ENV_VAR_1_VALUE
            - name: DB_HOST
              value: users-db
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              value: postgres
            - name: DATABASE
              value: users_service
            - name: USERS_SERVICE_URL
              value: learning.net.ar/users-service
            - name: COURSES_SERVICE_URL
              value: learning.net.ar/courses-service
            - name: MATH_SOLVER_URL
              value: learning.net.ar/math-solver

---
apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  type: ClusterIP
  ports:
    - name: "users-service"
      port: 80
      targetPort: 7000
  selector:
    app: users-service