apiVersion: v1
kind: PersistentVolume
metadata:
  name: users-db-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/postgresql/users-db-data"  # Adjust the path for each PostgreSQL instance

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: users-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-db
  template:
    metadata:
      labels:
        app: users-db
    spec:
      containers:
        - image: lorenzogl/users-db:GIT_SHA_SECRET
          imagePullPolicy: Always
          name: users-db
          env:
            - name: TEST_ENV_VAR
              value: TRIGGER_DEPLOY_1
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: users-db-storage
      volumes:
        - name: users-db-storage
          persistentVolumeClaim:
            claimName: users-db-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: users-db
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP
  ports:
    - name: "users-db"
      port: 5432
      targetPort: 5432
  selector:
    app: users-db
