name: Publish Database Docker Image + Deploy to Okteto
on:
  push:
    paths:
      - '**.yml'
      - '**Dockerfile-db'
    branches: [ master ]

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: autopilot-cluster-1    # cluster name
  GKE_ZONE: us-central1               # cluster zone

jobs:
  publish-docker-image-database:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: lorenzogl/users-db
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: ${{ github.sha }}
          dockerfile: Dockerfile-db

  push-db-okteto-pipeline:
    needs: publish-docker-image-database
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: Create and populate kubernetes/users-database.yml file
        env:
          MONGO_FULL_URL_SECRET: ${{ secrets.MONGO_URL }}
          GIT_SHA_SECRET: ${{ github.sha }}
        run: |
          touch kubernetes/users-database.yml
          sed "s|MONGO_URL_PLACEHOLDER|$MONGO_FULL_URL_SECRET|" kubernetes-templates/users-database.yml | sed "s|GIT_SHA_SECRET|$GIT_SHA_SECRET|" > kubernetes/users-database.yml
          echo "cat kubernetes/users-database.yml"
          cat kubernetes/users-database.yml

          echo "ls -a ."
          ls -a .

          echo "ls -a ${{ github.workspace }}"
          ls -a ${{ github.workspace }}
        shell: bash


      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up GKE credentials
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}

      - name: Deploy
        run:
          kubectl apply -f ./kubernetes/users-database.yml