name: Publish Backend Docker Image + Deploy to Okteto
on:
  push:
    branches: [ master ]

jobs:
  publish-docker-image-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: lorenzogl/users-service
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: ${{ github.sha }}
          dockerfile: Dockerfile

  push-okteto-pipeline:
    needs: publish-docker-image-backend
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: Create and populate kubernetes/users-service.yml file
        env:
          MONGO_FULL_URL_SECRET: ${{ secrets.MONGO_URL }}
          GIT_SHA_SECRET: ${{ github.sha }}
        run: |
          touch kubernetes/users-service.yml
          sed "s|MONGO_URL_PLACEHOLDER|$MONGO_FULL_URL_SECRET|" kubernetes-templates/users-service.yml | sed "s|GIT_SHA_SECRET|$GIT_SHA_SECRET|" > kubernetes/users-service.yml
          echo "cat kubernetes/users-service.yml"
          cat kubernetes/users-service.yml

          echo "ls -a ."
          ls -a .

          echo "ls -a ${{ github.workspace }}"
          ls -a ${{ github.workspace }}
        shell: bash


      - uses: okteto/login@latest
        with:
          token: ${{ secrets.OKTETO_TOKEN }}

      - name: "Activate personal namespace"
        uses: okteto/namespace@latest
        with:
          namespace: fiuba-lorenzolgz

      - name: "Create deployment"
        uses: okteto/apply@latest
        with:
          manifest: kubernetes/users-service.yml